id: geno
description: Intellegent provisionioning container for new Proxmox nodes

resources:
  - id: geno-container
    type: proxmox:container
    properties:
      hostname: geno
      template:
        name: debian-13*
      resource_pool: management
      privileged: true
      disks:
        rootfs:
          size: 16G
      cpu:
        # ISO extraction and repacking can be CPU intensive
        cores: 4
      memory:
        size: 1G
        swap: 1G
      network_interfaces:
        eth0:
          ipv4:
            address: 10.11.0.65/22
            gateway: 10.11.0.1
      startup_script:
        path: scripts/setup.sh
